---
  swagger: "2.0"
  info:
    title: "Example API"
    description: "Power your data"
    version: "1.0.0"
  host: localhost:9000
  schemes:
    - "http"
  consumes:
    - application/json
  produces:
    - application/json